name: MyDrops
version: '${project.version}'
main: net.maxxqc.mydrops.MyDrops
authors: [ Maxx_Qc ]
api-version: "1.13"
permissions:
  mydrops.bypass.pickup:
    description: Allow a player to pickup any item
    default: false
  mydrops.bypass.drop:
    description: Allow a player to drop items for anyone to pickup
    default: false
  mydrops.command.core:
    description: Gives access to the /mydrops command
    default: true
  mydrops.command.glowcolor:
    description: Give access to the /mydrops glowcolor command
    default: true
commands:
  mydrops:
    description: Main command to manage all of your drops
    usage: /mydrops [args]
    permission: mydrops.command.core