name: MyDrops
version: '${project.version}'
main: net.maxxqc.mydrops.MyDrops
authors: [ Maxx_Qc ]
api-version: "1.13"
softdepend:
  - MythicMobs
permissions:
  mydrops.bypass.pickup:
    description: Allow a player to pickup any item
    default: false
  mydrops.bypass.drop:
    description: Allow a player to drop items for anyone to pickup
    default: false
  mydrops.command.core:
    description: Gives access to the /mydrops command
    default: true
  mydrops.command.glowcolor:
    description: Give access to the /mydrops glowcolor command
    default: true
  mydrops.command.protection:
    description: Give access to the /mydrops protection command
    default: false
  mydrops.command.trash:
    description: Give access to the /mydrops trash command
    default: op
  mydrops.command.reload:
    description: Give access to the /mydrops reload command
    default: op
  mydrops.command.config:
    description: Give access to the /mydrops config command
    default: op
  mydrops.update:
    description: Anyone with this permission will receive informations from the updater when a new version is available
    default: op
commands:
  mydrops:
    description: Main command to manage all of your drops
    usage: /mydrops [args]
    permission: mydrops.command.core
    aliases:
      - md